version: '3.1'

services:
    mongo:
        image: mongo
        ports:
            - '27017:27017'
        restart: always
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: mydb
volumes:
    mongo-data:
