GET http://localhost:8081/api/v1/users/usuarios?offset=2&limit=1

###
DELETE  http://localhost:8081/api/v1/users/628802a553e681077cd2ab20

###
POST  http://localhost:8081/api/v1/users
content-type: application/json

{
    "nombre": "Francisco3",
    "correo":"email5@email.com",
    "password":"123456",
    "role":"USER_ROLE"
}

###
PUT   http://localhost:8081/api/v1/users/6287fdf708431926ab99d839
content-type: application/json

{
    "nombre": "Carlos Update2",
    "google":true,
    "_id":"6287fdf708431926ab99d839"
}
