GET http://localhost:8081/api/v1/users

###
DELETE  http://localhost:8081/api/v1/users

###
POST  http://localhost:8081/api/v1/users
content-type: application/json

{
    "name": "Carlos"
}

###
PUT   http://localhost:8081/api/v1/users/10?apikey=hoooolllaa
content-type: application/json

{
    "name": "Carlos"
}
